// Mocks generated by Mockito 5.2.0 from annotations
// in flutter_http/test/widget_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:flutter_http/client/model.dart' as _i2;
import 'package:flutter_http/client/todo_client.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeTodo_0 extends _i1.Fake implements _i2.Todo {}

/// A class which mocks [TodoClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodoClient extends _i1.Mock implements _i3.TodoClient {
  MockTodoClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Todo>> getTodos() =>
      (super.noSuchMethod(Invocation.method(#getTodos, []),
              returnValue: Future<List<_i2.Todo>>.value(<_i2.Todo>[]))
          as _i4.Future<List<_i2.Todo>>);
  @override
  _i4.Future<_i2.Todo> createTodo(String? title) =>
      (super.noSuchMethod(Invocation.method(#createTodo, [title]),
              returnValue: Future<_i2.Todo>.value(_FakeTodo_0()))
          as _i4.Future<_i2.Todo>);
}
